apiVersion: v1
kind: Service
metadata:
  name: bookinfo
  namespace: default
spec:
  type: NodePort
  selector:
    app: bookinfo # 根据kubectl get pod --show-labels 获得
  ports:
    - port: 80 # Service集群内通过80访问
      targetPort: 8080 # 目标pod的端口
      # 30000 - 32767
      nodePort: 30080 # Service 对外暴露的端口

